# Generated by Django 3.1.1 on 2020-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.CharField(max_length=50)),
                ('plateNumber', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('totalSeats', models.IntegerField()),
                ('busFare', models.FloatField()),
                ('departureTime', models.TimeField()),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
