# Generated by Django 3.1.1 on 2020-11-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20201125_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailAddress', models.CharField(max_length=50)),
                ('contactNumber', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
    ]
