# Generated by Django 3.1.1 on 2020-11-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Buses',
        ),
        migrations.AlterModelTable(
            name='buses',
            table='Buses',
        ),
    ]
