# Generated by Django 3.1.1 on 2020-11-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_auto_20201125_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='img',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
