# Generated by Django 3.1.1 on 2020-12-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver',
        ),
    ]
