# Generated by Django 3.1.1 on 2020-12-08 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dateReservation',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='robust.user'),
        ),
    ]
