# Generated by Django 3.1.1 on 2020-12-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='img',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
