# Generated by Django 3.1.1 on 2020-12-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0002_remove_bus_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
