# Generated by Django 3.1.1 on 2020-12-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0002_booking_datereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateReservation',
            field=models.DateField(default=None),
        ),
    ]
