# Generated by Django 3.1.1 on 2020-12-04 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0003_auto_20201204_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dateReservation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
