# Generated by Django 3.1.1 on 2020-12-02 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0003_auto_20201202_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
