# Generated by Django 3.1.1 on 2020-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0004_remove_booking_datereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dateReservation',
            field=models.DateField(default=None),
        ),
    ]
