# Generated by Django 3.1.1 on 2020-11-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('busNumber', models.AutoField(primary_key=True, serialize=False)),
                ('busName', models.CharField(max_length=50)),
                ('plateNumber', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('totalSeats', models.IntegerField()),
                ('busFare', models.FloatField()),
                ('departureTime', models.TimeField()),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
    ]
