# Generated by Django 3.1.1 on 2020-11-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='head.bus')),
                ('seatNumber', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Booking',
            },
            bases=('head.bus',),
        ),
    ]
