# Generated by Django 3.1.1 on 2020-11-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
